import { useState } from "react";
import { Download, Printer, Search } from "lucide-react";
import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import { fabricCuttingApi as api } from "../../api/fabricCuttingApi.js";
import QRGenerator from "../../components/qr/QRGenerator.jsx";

export default function FabricQrPrintPage({notify}){
 const [number,setNumber]=useState(""),[inward,setInward]=useState(null),[rolls,setRolls]=useState([]),[cfg,setCfg]=useState({width:70,height:48,qr:23,gapX:4,gapY:4,columns:2,page:"a4"});
 async function find(){try{const [i,r]=await Promise.all([api.inward(number),api.bundles(number)]);setInward(i);setRolls(r)}catch(e){setInward(null);notify?.(e.message)}}
 async function download(){if(!rolls.length)return;const pdf=new jsPDF({unit:"mm",format:cfg.page});let x=10,y=10;for(let i=0;i<rolls.length;i++){const r=rolls[i];if(y+cfg.height>pdf.internal.pageSize.height-8){pdf.addPage();x=10;y=10}pdf.rect(x,y,cfg.width,cfg.height);const q=await QRCode.toDataURL(`${location.origin}/fabric-roll/${r.qrToken}`,{margin:1,width:300});pdf.addImage(q,"PNG",x+3,y+3,cfg.qr,cfg.qr);pdf.setFontSize(7);const tx=x+cfg.qr+6;pdf.text([`${r.fabricGroup} / ${r.fabricName}`,`${r.colour} · Dia ${r.dia}`,`Dyeing: ${r.dyeingName||"-"}`,`Compacting: ${r.compactingName||"-"}`,`DC: ${inward.dcNo||inward.lotDcNo||"-"}`,`WT: ${r.originalWeightKg} KG`,`ROLL ${r.rollNo} OF ${rolls.length}`],tx,y+7);if((i+1)%Number(cfg.columns)===0){x=10;y+=Number(cfg.height)+Number(cfg.gapY)}else x+=Number(cfg.width)+Number(cfg.gapX)}pdf.save(`${inward.inwardNo}-roll-qr.pdf`)}
 return <section className="classic-page"><div className="classic-title"><div><small>FABRIC INWARD</small><h2>Fabric Roll QR Print</h2><p>Generate one cut-ready rectangular QR label for every inward roll.</p></div></div><div className="classic-card"><div className="lookup-bar"><input placeholder="Inward Number" value={number} onChange={e=>setNumber(e.target.value)}/><button className="primary" onClick={find}><Search/> Load Rolls</button></div><div className="qr-config">{[["width","Width mm"],["height","Height mm"],["qr","QR mm"],["gapX","Horizontal Gap"],["gapY","Vertical Gap"],["columns","Labels / Row"]].map(([k,l])=><label key={k}>{l}<input type="number" value={cfg[k]} onChange={e=>setCfg({...cfg,[k]:e.target.value})}/></label>)}<label>Page<select value={cfg.page} onChange={e=>setCfg({...cfg,page:e.target.value})}><option value="a4">A4</option><option value="a5">A5</option></select></label></div></div>{inward&&<><div className="page-actions"><button onClick={()=>window.print()}><Printer/> Print All</button><button className="primary" onClick={download}><Download/> Download PDF</button></div><div className="fabric-label-grid scoped-print-target" style={{gridTemplateColumns:`repeat(${cfg.columns},${cfg.width}mm)`,gap:`${cfg.gapY}mm ${cfg.gapX}mm`}}>{rolls.map(r=><article key={r._id} style={{width:`${cfg.width}mm`,height:`${cfg.height}mm`}}><QRGenerator size={Math.round(Number(cfg.qr)*3.78)} value={`${location.origin}/fabric-roll/${r.qrToken}`}/><div><b>{r.fabricGroup} / {r.fabricName}</b><span>{r.colour} · Dia {r.dia}</span><span>Dyeing: {r.dyeingName||"—"}</span><span>Compacting: {r.compactingName||"—"}</span><span>DC: {inward.dcNo||inward.lotDcNo||"—"}</span><strong>{r.originalWeightKg} KG · ROLL {r.rollNo}/{rolls.length}</strong></div></article>)}</div></>}</section>
}
