import { useEffect, useMemo, useState } from "react";
import { Download, Play, RefreshCw, Save } from "lucide-react";
import { exportCsv } from "../../api.js";
import { getCuttingMachinePlans, getCuttingMachineStatus, saveCuttingMachinePlan, cuttingMachineAction, transferCuttingMachinePlan } from "../../api/productionApi.js";

const blank = { machineType: "SPREADER", machineCode: "", planNo: "", colour: "", size: "ALL", pcs: "", priority: 1 };
const allowedActions = (row) => {
  if (["COMPLETED","PUBLISHED"].includes(row.status)) return [];
  if (row.status === "BREAKDOWN") return ["RESUME"];
  if (["PAUSED","CHANGE"].includes(row.status)) return ["RESUME","BREAKDOWN"];
  if (["QUEUED","READY"].includes(row.status)) return ["START","CHANGE","BREAKDOWN"];
  return row.machineType === "SPREADER" ? ["COMPLETE","CHANGE","BREAKDOWN","BREAK"] : ["COMPLETE","CHANGE","BREAKDOWN","BREAK"];
};

export default function CuttingMachinePlanPage({ notify, mode = "plan" }) {
  const [form, setForm] = useState(blank);
  const [rows, setRows] = useState([]);
  const [machines, setMachines] = useState([]);
  const [search, setSearch] = useState("");
  async function load() { const [plans, status] = await Promise.all([getCuttingMachinePlans(), getCuttingMachineStatus()]); setRows(plans); setMachines(status); }
  useEffect(() => { load().catch((e) => notify?.(e.message)); }, []);
  const availableMachines = machines.filter((m) => m.machineType.toUpperCase() === (form.machineType === "SPREADER" ? "SPREADER" : "CUTTER") && m.status !== "Breakdown");
  const filtered = useMemo(() => rows.filter((r) => `${r.planNo} ${r.dcNo} ${r.machineCode} ${r.colour} ${r.status}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  async function submit(e) { e.preventDefault(); try { await saveCuttingMachinePlan(form); setForm(blank); await load(); notify?.("Machine plan assigned / queued"); } catch (error) { notify?.(error.message); } }
  async function act(row, action) { const reason = ["CHANGE", "BREAKDOWN", "BREAK"].includes(action) ? window.prompt(`${action} reason`) || "" : ""; try { await cuttingMachineAction(row._id, action, reason); await load(); notify?.(row.machineType === "SPREADER" && action === "COMPLETE" ? `${row.planNo}: Spreader completed and moved to Cutter` : `${row.planNo}: ${action}`); } catch (error) { notify?.(error.message); } }
  async function transfer(row) { const machineCode = window.prompt("Target machine code"); if (!machineCode) return; try { await transferCuttingMachinePlan(row._id, machineCode, "Operator transfer"); await load(); } catch (error) { notify?.(error.message); } }
  async function assignCutter(row) { const cutters=machines.filter(m=>String(m.machineType).toUpperCase()==='CUTTER'&&m.status!=='Breakdown'); if(!cutters.length)return notify?.("Cutter machine இல்லை. Cutting Master-ல் Cutter create அல்லது Resume செய்யவும்"); const machineCode=cutters.length===1?cutters[0].machineCode:window.prompt(`Cutter code: ${cutters.map(x=>x.machineCode).join(', ')}`,cutters[0].machineCode); if(!machineCode)return; try{await saveCuttingMachinePlan({machineType:'CUTTER',machineCode,planNo:row.planNo,colour:row.colour,size:row.size,pcs:row.pcs,priority:1});await load();notify?.(`${row.planNo} moved to ${machineCode}`)}catch(error){notify?.(error.message)} }
  if (mode === "status") return <StatusView machines={machines} rows={filtered} search={search} setSearch={setSearch} act={act} transfer={transfer} assignCutter={assignCutter} />;
  if (mode === "timeline-spreader") return <TimelineView type="SPREADER" rows={filtered} search={search} setSearch={setSearch} />;
  if (mode === "timeline-cutter") return <TimelineView type="CUTTER" rows={filtered} search={search} setSearch={setSearch} />;
  if (mode === "time-history") return <TimeHistoryView rows={filtered} search={search} setSearch={setSearch} />;
  if (mode === "plan-status") return <HistoryView rows={filtered} search={search} setSearch={setSearch} />;
  return <section className="classic-page"><div className="classic-title"><div><small>CUTTING DEPARTMENT · MACHINE PLAN</small><h2>Machine Plan</h2><p>Assign Spreader/Cutter work, control live status and maintain machine queues.</p></div></div>
    <form className="classic-card machine-plan-form" onSubmit={submit}><div className="form-grid">
      <label><span>Machine Type</span><select value={form.machineType} onChange={(e) => setForm({ ...form, machineType: e.target.value, machineCode: "" })}><option>SPREADER</option><option>CUTTER</option></select></label>
      <label><span>Machine</span><select required value={form.machineCode} onChange={(e) => setForm({ ...form, machineCode: e.target.value })}><option value="">Select</option>{availableMachines.map((m) => <option key={m.machineCode}>{m.machineCode}</option>)}</select></label>
      {['planNo','colour','size','pcs','priority'].map((key) => <label key={key}><span>{key}</span><input required={key !== 'size'} type={['pcs','priority'].includes(key) ? 'number' : 'text'} min="1" value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}
    </div><button className="primary machine-assign-button"><Save /> Assign</button></form>
    <div className="classic-card"><div className="table-toolbar"><h3>Live & Queue Plans</h3><button onClick={load}><RefreshCw /> Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Machine</th><th>Type</th><th>Plan / DC</th><th>Colour</th><th>Size</th><th>PCS</th><th>Queue</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((row) => <tr key={row._id}><td>{row.machineCode}</td><td>{row.machineType}</td><td>{row.planNo}<small>{row.dcNo}</small></td><td>{row.colour}</td><td>{row.size}</td><td>{row.pcs}</td><td>{row.queuePosition === 0 ? 'LIVE' : row.queuePosition}</td><td><b className={`status-pill status-${row.status.toLowerCase()}`}>{row.status === 'COMPLETED' ? '👍 COMPLETED' : row.status === 'PUBLISHED' ? '✓ COMPLETE → CUTTER' : row.status}</b></td><td><div className="machine-actions">{allowedActions(row).map((a) => <button type="button" key={a} onClick={() => act(row,a)}><Play />{a}</button>)}{!['COMPLETED','PUBLISHED'].includes(row.status)&&<button type="button" onClick={() => transfer(row)}>Transfer</button>}</div></td></tr>)}</tbody></table></div></div>
  </section>;
}

function HistoryView({ rows, search, setSearch }) { return <section className="classic-page"><div className="classic-title"><div><small>CUTTING DEPARTMENT</small><h2>Plan Number Status</h2><p>Full Spreader/Cutter stage, queue and action history.</p></div><button onClick={() => exportCsv("plan-number-status.csv", rows)}><Download /> Excel</button></div><div className="classic-card"><input placeholder="Plan / DC / Machine" value={search} onChange={(e) => setSearch(e.target.value)} /><div className="table-wrap"><table><thead><tr><th>Plan</th><th>DC</th><th>Machine</th><th>Stage</th><th>Colour</th><th>Size</th><th>PCS</th><th>Queue</th><th>Status</th><th>History</th></tr></thead><tbody>{rows.map((r) => <tr key={r._id}><td>{r.planNo}</td><td>{r.dcNo}</td><td>{r.machineCode}</td><td>{r.machineType}</td><td>{r.colour}</td><td>{r.size}</td><td>{r.pcs}</td><td>{r.queuePosition}</td><td>{r.status}</td><td>{(r.events||[]).map((e) => `${e.action} ${new Date(e.at).toLocaleString()}`).join(' · ')}</td></tr>)}</tbody></table></div></div></section>; }

const elapsedHours=(row)=>{const start=row.startedAt||((row.status==='RUNNING'||row.completedAt)?row.createdAt:null);if(!start)return 0;const end=row.completedAt?new Date(row.completedAt):new Date();return Math.max(0,(end-new Date(start))/3600000)};
<<<<<<< HEAD
function TimelineView({type,rows,search,setSearch}){const data=rows.filter(r=>r.machineType===type);return <section className="classic-page"><div className="classic-title"><div><small>CUTTING DEPARTMENT · TIME STATUS</small><h2>{type==='SPREADER'?'Spreader':'Cutter'} Timeline</h2><p>DC running/completed status, working hours and production hours.</p></div><button onClick={()=>exportCsv(`${type.toLowerCase()}-timeline.csv`,data)}><Download/> Excel</button></div><div className="classic-card"><input placeholder="Plan / DC / Machine" value={search} onChange={e=>setSearch(e.target.value)}/><div className="time-kpis"><span><small>Running DC</small><b>{data.filter(r=>r.status==='RUNNING').length}</b></span><span><small>Completed DC</small><b>{data.filter(r=>['COMPLETED','PUBLISHED'].includes(r.status)).length}</b></span><span><small>Queue</small><b>{data.filter(r=>['QUEUED','READY'].includes(r.status)).length}</b></span><span><small>Production Hours</small><b>{data.reduce((s,r)=>s+elapsedHours(r),0).toFixed(2)} h</b></span></div><CuttingGantt data={data}/><h3>Detailed Time Status</h3><div className="table-wrap"><table><thead><tr><th>Date</th><th>Plan / DC</th><th>Machine</th><th>Colour</th><th>Size</th><th>PCS</th><th>Start</th><th>End</th><th>Work Hrs</th><th>Production Hrs</th><th>Status</th></tr></thead><tbody>{data.length?data.map(r=>{const start=r.startedAt||((r.status==='RUNNING'||r.completedAt)?r.createdAt:null);return <tr key={r._id}><td>{new Date(r.createdAt).toLocaleDateString()}</td><td>{r.planNo}<small>{r.dcNo}</small></td><td>{r.machineCode}</td><td>{r.colour}</td><td>{r.size}</td><td>{r.pcs}</td><td>{start?new Date(start).toLocaleString():'—'}</td><td>{r.completedAt?new Date(r.completedAt).toLocaleString():r.status==='RUNNING'?'LIVE':'—'}</td><td>{elapsedHours(r).toFixed(2)} h</td><td>{elapsedHours(r).toFixed(2)} h</td><td>{r.status==='PUBLISHED'?'COMPLETED':r.status}</td></tr>}):<tr><td colSpan="11">No {type.toLowerCase()} plan data</td></tr>}</tbody></table></div></div></section>}

function CuttingGantt({ data }) {
  const [selected, setSelected] = useState("");
  const machines = [...new Set(data.map((row) => row.machineCode))];
  const dayStart = new Date(); dayStart.setHours(0, 0, 0, 0);
  const dayEnd = new Date(dayStart); dayEnd.setDate(dayEnd.getDate() + 1);
  const segment = (row) => {
    const start = new Date(row.startedAt || row.createdAt), end = new Date(row.completedAt || Date.now());
    const from = Math.max(start, dayStart), to = Math.min(end, dayEnd);
    if (to <= from || (!row.startedAt && row.status !== "RUNNING" && !row.completedAt)) return null;
    return { left: (from - dayStart) / 864000, width: (to - from) / 864000, start: new Date(from), end: new Date(to) };
  };
  const week = Array.from({ length: 7 }, (_, index) => {
    const from = new Date(dayStart); from.setDate(from.getDate() - (6 - index));
    const to = new Date(from); to.setDate(to.getDate() + 1);
    const jobs = data.filter((row) => row.machineCode === selected).filter((row) => new Date(row.startedAt || row.createdAt) < to && new Date(row.completedAt || Date.now()) > from);
    const hours = jobs.reduce((sum, row) => { const a = Math.max(new Date(row.startedAt || row.createdAt), from), b = Math.min(new Date(row.completedAt || Date.now()), to); return sum + Math.max(0, b - a) / 3600000; }, 0);
    return { from, jobs, hours, pcs: jobs.reduce((sum, row) => sum + Number(row.pcs || 0), 0) };
  });
  return <div className="cutting-gantt-block"><h3>Today · 24 Hour Gantt Chart</h3><p className="form-hint">Machine row click செய்தால் கீழே One Week Report வரும்.</p><div className="machine-gantt"><div className="gantt-hours"><b>Machine</b><div>{Array.from({ length: 24 }, (_, hour) => <span key={hour}>{String(hour).padStart(2, "0")}</span>)}</div><b>Status</b></div>{machines.map((code) => { const jobs = data.filter((row) => row.machineCode === code); const live = jobs.some((row) => row.status === "RUNNING"); return <button type="button" className={`gantt-machine-row ${selected === code ? "selected" : ""}`} key={code} onClick={() => setSelected(selected === code ? "" : code)}><span className="gantt-machine-name"><b>{code}</b><small>{jobs.find((row) => row.status === "RUNNING")?.dcNo || jobs[0]?.dcNo || "No DC"}</small></span><span className="gantt-track">{jobs.map((row) => { const item = segment(row); return item && <i key={row._id} className={row.status === "RUNNING" ? "production" : "completed"} style={{ left: `${item.left}%`, width: `${Math.max(item.width, 0.4)}%` }} title={`${row.planNo}/${row.dcNo} ${item.start.toLocaleTimeString()} - ${item.end.toLocaleTimeString()}`} />; })}</span><span className={`machine-status ${live ? "status-running" : "status-available"}`}>{live ? "RUNNING" : "IDLE"}</span></button>; })}</div>{selected && <div className="week-plan-report"><h3>{selected} · One Week Plan Report</h3><div className="table-wrap"><table><thead><tr><th>Date</th><th>Plan / DC</th><th>PCS</th><th>Work Hrs</th><th>Production Hrs</th><th>Status</th></tr></thead><tbody>{week.map((row) => <tr key={row.from.toISOString()}><td>{row.from.toLocaleDateString()}</td><td>{row.jobs.map((job) => `${job.planNo}/${job.dcNo}`).join(", ") || "—"}</td><td>{row.pcs}</td><td>{row.hours.toFixed(2)} h</td><td>{row.hours.toFixed(2)} h</td><td>{row.jobs.some((job) => job.status === "RUNNING") ? "RUNNING" : row.jobs.length ? "COMPLETED" : "NO PLAN"}</td></tr>)}</tbody></table></div></div>}</div>;
}
=======
function TimelineView({type,rows,search,setSearch}){const data=rows.filter(r=>r.machineType===type);return <section className="classic-page"><div className="classic-title"><div><small>CUTTING DEPARTMENT · TIME STATUS</small><h2>{type==='SPREADER'?'Spreader':'Cutter'} Timeline</h2><p>DC running/completed status, working hours and production hours.</p></div><button onClick={()=>exportCsv(`${type.toLowerCase()}-timeline.csv`,data)}><Download/> Excel</button></div><div className="classic-card"><input placeholder="Plan / DC / Machine" value={search} onChange={e=>setSearch(e.target.value)}/><div className="time-kpis"><span><small>Running DC</small><b>{data.filter(r=>r.status==='RUNNING').length}</b></span><span><small>Completed DC</small><b>{data.filter(r=>['COMPLETED','PUBLISHED'].includes(r.status)).length}</b></span><span><small>Queue</small><b>{data.filter(r=>['QUEUED','READY'].includes(r.status)).length}</b></span><span><small>Production Hours</small><b>{data.reduce((s,r)=>s+elapsedHours(r),0).toFixed(2)} h</b></span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Plan / DC</th><th>Machine</th><th>Colour</th><th>Size</th><th>PCS</th><th>Start</th><th>End</th><th>Work Hrs</th><th>Production Hrs</th><th>Status</th></tr></thead><tbody>{data.length?data.map(r=>{const start=r.startedAt||((r.status==='RUNNING'||r.completedAt)?r.createdAt:null);return <tr key={r._id}><td>{new Date(r.createdAt).toLocaleDateString()}</td><td>{r.planNo}<small>{r.dcNo}</small></td><td>{r.machineCode}</td><td>{r.colour}</td><td>{r.size}</td><td>{r.pcs}</td><td>{start?new Date(start).toLocaleString():'—'}</td><td>{r.completedAt?new Date(r.completedAt).toLocaleString():r.status==='RUNNING'?'LIVE':'—'}</td><td>{elapsedHours(r).toFixed(2)} h</td><td>{elapsedHours(r).toFixed(2)} h</td><td>{r.status==='PUBLISHED'?'COMPLETED':r.status}</td></tr>}):<tr><td colSpan="11">No {type.toLowerCase()} plan data</td></tr>}</tbody></table></div></div></section>}
>>>>>>> 30800dc97d58c3fe1283b8654af8a74dd6b48880

function TimeHistoryView({rows,search,setSearch}){const plans=[...new Set(rows.map(r=>r.planNo))].map(planNo=>{const stages=rows.filter(r=>r.planNo===planNo),spreader=stages.filter(r=>r.machineType==='SPREADER').at(0),cutter=stages.filter(r=>r.machineType==='CUTTER').at(0);return {planNo,dcNo:spreader?.dcNo||cutter?.dcNo,spreader,cutter}});return <section className="classic-page"><div className="classic-title"><div><small>CUTTING DEPARTMENT · TIME STATUS</small><h2>Cutting Time History</h2><p>Each Plan Number’s current Spreader/Cutter location and completion status.</p></div><button onClick={()=>exportCsv('cutting-time-history.csv',plans.map(x=>({planNo:x.planNo,dcNo:x.dcNo,spreader:x.spreader?.machineCode||'',spreaderStatus:x.spreader?.status||'',cutter:x.cutter?.machineCode||'',cutterStatus:x.cutter?.status||'WAITING'})))}><Download/> Excel</button></div><div className="classic-card"><input placeholder="Plan / DC / Machine" value={search} onChange={e=>setSearch(e.target.value)}/><div className="table-wrap"><table><thead><tr><th>Plan No</th><th>DC No</th><th>Spreader</th><th>Spreader Status</th><th>Cutter</th><th>Cutter Status</th><th>Current Stage</th><th>Total Hours</th></tr></thead><tbody>{plans.map(x=><tr key={x.planNo}><td>{x.planNo}</td><td>{x.dcNo}</td><td>{x.spreader?.machineCode||'—'}</td><td>{x.spreader?.status==='PUBLISHED'?'COMPLETED':x.spreader?.status||'—'}</td><td>{x.cutter?.machineCode||'—'}</td><td>{x.cutter?.status||'WAITING FOR CUTTER'}</td><td>{x.cutter?(x.cutter.status==='COMPLETED'?'CUTTING COMPLETED':`CUTTER ${x.cutter.status}`):x.spreader?.status==='PUBLISHED'?'WAITING FOR CUTTER':`SPREADER ${x.spreader?.status||'—'}`}</td><td>{(elapsedHours(x.spreader||{})+elapsedHours(x.cutter||{})).toFixed(2)} h</td></tr>)}</tbody></table></div></div></section>}

function StatusView({ machines, rows, search, setSearch, act, transfer, assignCutter }) { const cutterRows=rows.filter(r=>r.machineType==='CUTTER');const incoming=rows.filter(r=>r.machineType==='SPREADER'&&r.status==='PUBLISHED'&&!rows.some(c=>String(c.upstreamAssignmentId||'')===String(r._id)));return <section className="classic-page"><div className="classic-title"><div><small>CUTTING DEPARTMENT</small><h2>Cutter Status</h2><p>Spreader completed work, Cutter live plan, queue and cutting completion actions.</p></div><button onClick={() => exportCsv("cutter-machine-status.csv", [...incoming,...cutterRows])}><Download /> Excel</button></div><div className="classic-card"><input placeholder="Machine / Plan" value={search} onChange={(e) => setSearch(e.target.value)} /><h3>Incoming from Spreader</h3><div className="table-wrap"><table><thead><tr><th>Plan / DC</th><th>Colour</th><th>Size</th><th>PCS</th><th>Status</th><th>Action</th></tr></thead><tbody>{incoming.length?incoming.map(r=><tr key={r._id}><td>{r.planNo}<small>{r.dcNo}</small></td><td>{r.colour}</td><td>{r.size}</td><td>{r.pcs}</td><td>WAITING FOR CUTTER</td><td><button className="primary compact-action" onClick={()=>assignCutter(r)}>Assign Cutter</button></td></tr>):<tr><td colSpan="6">No pending Spreader work</td></tr>}</tbody></table></div><h3>Cutter Live & Queue</h3><div className="table-wrap"><table><thead><tr><th>Cutter</th><th>Plan / DC</th><th>Colour</th><th>Size</th><th>PCS</th><th>Queue</th><th>Status</th><th>Action</th></tr></thead><tbody>{cutterRows.length?cutterRows.map(r=><tr key={r._id}><td>{r.machineCode}</td><td>{r.planNo}<small>{r.dcNo}</small></td><td>{r.colour}</td><td>{r.size}</td><td>{r.pcs}</td><td>{r.queuePosition===0?'LIVE':r.queuePosition}</td><td>{r.status==='COMPLETED'?'👍 COMPLETED':r.status}</td><td><div className="machine-actions">{allowedActions(r).map(a=><button key={a} onClick={()=>act(r,a)}><Play/>{a}</button>)}{!['COMPLETED'].includes(r.status)&&<button onClick={()=>transfer(r)}>Transfer</button>}</div></td></tr>):<tr><td colSpan="8">No Cutter work assigned</td></tr>}</tbody></table></div><div className="machine-status-cards">{machines.filter(m=>String(m.machineType).toUpperCase()==='CUTTER').map((m) => { const list = m.assignments || []; const live = list.find((r) => r.status === 'RUNNING'); const queue = list.filter((r) => ['QUEUED','READY'].includes(r.status)); return <article key={m._id}><h3>{m.machineCode}</h3><b>Cutter · {m.status}</b><p>Live: {live ? `${live.planNo} / ${live.dcNo}` : 'No live plan'}</p><p>Queue: {queue.map((r) => `${r.queuePosition}. ${r.planNo}`).join(', ') || 'Empty'}</p><p>Completed: {list.filter((r) => r.status==='COMPLETED').length}</p></article>; })}</div></div></section>; }
