import {fail,money,ratio,safeInteger} from './policy.js';
export const DEPARTMENTS=['STITCHING','INWARD','CHECKING','IRONING','PACKING','DISPATCH','WAREHOUSE','SHOP','MARKETING'];
export const ADMIN_ROLES=['admin','company_admin'];
export function pieces(value){const n=Number(value);if(value===''||value==null||typeof value==='boolean'||!Number.isSafeInteger(n)||n<=0||n>1000000)fail('Use 1–1,000,000 whole pieces');return n;}
export function names(values){if(!Array.isArray(values)||!values.length||values.length>100)fail('Use 1–100 operation names');const out=values.map(v=>String(v).trim());if(out.some(v=>!v||v.length>80)||new Set(out).size!==out.length)fail('Operation names must be unique and non-empty');return out;}
export function checkSplit(input,available){const out={};for(const k of ['good','rework','oil','reject']){const v=Number(input[k]||0);if(!Number.isSafeInteger(v)||v<0)fail('Checking quantities must be whole pieces');out[k]=v;}const total=Object.values(out).reduce((a,b)=>a+b,0);if(total<=0||total>available)fail('Checking split exceeds available pieces');return {...out,total};}
export function allowedDepartment(user,department,write=false){if(['saas_super_admin','support_viewer'].includes(user?.role))return false;if(ADMIN_ROLES.includes(user?.role))return true;const p=user?.permissions||[];return p.includes(`department.${department.toLowerCase()}.${write?'write':'read'}`)||(!write&&p.includes(`department.${department.toLowerCase()}.write`));}
export function enabledDepartment(company,department){const selected=company.enabledDepartments?.slice(0,company.entitlements?.maxDepartments||100);const licensed=(company.entitlements?.modules||[]).filter(x=>DEPARTMENTS.includes(x));return (!selected?.length||selected.includes(department))&&(!licensed.length||licensed.includes(department));}
export function allowedShop(user,code){return ADMIN_ROLES.includes(user?.role)||(user?.permissions||[]).includes(`shop.${code}`);}
export function stageAfter(stage,operations){if(stage==='STITCHING_READY')return 'OP:0';if(stage.startsWith('OP:')){const i=Number(stage.slice(3));if(!Number.isInteger(i)||i<0||i>=operations.length)fail('Invalid operation');return i+1===operations.length?'STITCHED':`OP:${i+1}`;}const next={STITCHED:'CHECKING',GOOD:'IRONING',IRONING:'IRONED',REWORK:'REWORK_DONE',REWORK_DONE:'CHECKING',OIL:'OIL_DONE',OIL_DONE:'CHECKING',IRONED:'PACKED'};if(!next[stage])fail('Use the department-specific movement');return next[stage];}
export function packingRequirements(rows,count){if(!Array.isArray(rows)||!rows.length||rows.length>100)fail('Packing master requires 1–100 materials');return rows.map(r=>{const per=pieces(r.perPieces),qty=Number(r.quantity);if(!Number.isFinite(qty)||qty<=0||!Number.isSafeInteger(Math.round(qty*1000))||Math.abs(qty*1000-Math.round(qty*1000))>1e-6)fail('Packing consumption supports three decimals');return {sku:String(r.sku||'').toUpperCase(),qty:Math.ceil(count/per)*Math.round(qty*1000)};});}
export function saleTotals(count,unitPrice,taxPercent=0,discount=0){const net=safeInteger(pieces(count)*money(unitPrice)-money(discount));const rate=Number(taxPercent);if(![0,0.1,0.25,1,1.5,3,5,6,9,12,18,28].includes(rate))fail('Select a supported tax rate');const tax=ratio(net,Math.round(rate*100),10000);return {net,tax,gross:safeInteger(net+tax)};}
export function demandSuggestion(sold,days,leadDays,safety,stock,inTransit){if(![sold,days,leadDays,safety,stock,inTransit].every(Number.isFinite)||days<=0||[sold,leadDays,safety,stock,inTransit].some(v=>v<0))fail('Invalid demand calculation');return Math.max(0,Math.ceil(sold/days*leadDays+safety-stock-inTransit));}
