import { useEffect,useState } from "react";
import { api } from "../api/http.js";
import { Empty,Field,PageTitle } from "../components/Common.jsx";
const blank=()=>({itemCode:"",itemName:"",brand:"",style:"",fabricGroup:"",fabricType:"",fabricPriority:1,numberOfColours:1,colours:[{name:"",priority:1}],sizeMeasurements:[],changeReason:""});
const size=()=>({size:"",dia:"",cuttingWeightPerPieceKg:"",foldingWeightPerPieceKg:""});
export default function BomPage(){const[rows,setRows]=useState([]),[form,setForm]=useState(blank()),[loading,setLoading]=useState(true),[modal,setModal]=useState(false);
 const load=()=>{setLoading(true);api("/masters/boms").then(setRows).finally(()=>setLoading(false))};useEffect(load,[]);
 const setColours=n=>setForm(f=>({...f,numberOfColours:n,colours:Array.from({length:Number(n)||1},(_,i)=>f.colours[i]||{name:"",priority:i+1})}));
 const save=async e=>{e.preventDefault();if(form.sizeMeasurements.length===0)throw new Error("Add at least one size measurement");await api("/masters/boms",{method:"POST",body:JSON.stringify(form)});setForm(blank());load();};
 const edit=r=>{setForm({...r,changeReason:""});window.scrollTo({top:0,behavior:"smooth"})};
 const action=async(r,a)=>{const body=a==="reject"?JSON.stringify({reason:prompt("Rejection reason")||"Rejected by admin"}):undefined;await api(`/masters/boms/${r._id}/${a}`,{method:"PATCH",body});load();};
 return <><PageTitle title="Garment BOM" text="Version controlled fabric and size measurements. Approved revisions alone become active." rows={rows} file="garment-bom.csv"/>
 <form className="card form" onSubmit={save}><h3>{form._id?`Revise ${form.bomNo}`:"New BOM (number auto generated)"}</h3><div className="grid">
 {["itemCode","itemName","brand","style","fabricGroup","fabricType"].map(k=><Field key={k} label={k.replaceAll(/([A-Z])/g," $1")}><input required={k!=="brand"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}
 <Field label="Fabric Priority"><input type="number" min="1" value={form.fabricPriority} onChange={e=>setForm({...form,fabricPriority:Number(e.target.value)})}/></Field>
 <Field label="No. of Colours"><input type="number" min="1" value={form.numberOfColours} onChange={e=>setColours(e.target.value)}/></Field></div>
 <div className="subgrid">{form.colours.map((c,i)=><Field key={i} label={`Colour ${i+1}`}><input required value={c.name} onChange={e=>setForm({...form,colours:form.colours.map((x,j)=>j===i?{name:e.target.value,priority:i+1}:x)})}/></Field>)}</div>
 {form._id&&<Field label="Change Reason"><input required value={form.changeReason} onChange={e=>setForm({...form,changeReason:e.target.value})}/></Field>}
 <button type="button" className="secondary" onClick={()=>setModal(true)}>Sizes & Measurements ({form.sizeMeasurements.length})</button> <button>Submit for Approval</button></form>
 {modal&&<div className="modalback"><div className="modal card"><h3>Size Measurements</h3><div className="table"><table><thead><tr><th>Size</th><th>Dia</th><th>Cutting WT/PCS</th><th>Folding WT/PCS</th><th>Total WT/PCS</th><th/></tr></thead><tbody>{form.sizeMeasurements.map((r,i)=><tr key={i}>{["size","dia","cuttingWeightPerPieceKg","foldingWeightPerPieceKg"].map(k=><td key={k}><input type={k.includes("Kg")?"number":"text"} step="0.000001" value={r[k]} onChange={e=>setForm({...form,sizeMeasurements:form.sizeMeasurements.map((x,j)=>j===i?{...x,[k]:e.target.value}:x)})}/></td>)}<td>{(Number(r.cuttingWeightPerPieceKg||0)+Number(r.foldingWeightPerPieceKg||0)).toFixed(6)}</td><td><button type="button" className="danger" onClick={()=>setForm({...form,sizeMeasurements:form.sizeMeasurements.filter((_,j)=>j!==i)})}>×</button></td></tr>)}</tbody></table></div><button type="button" onClick={()=>setForm({...form,sizeMeasurements:[...form.sizeMeasurements,size()]})}>Add Row</button> <button type="button" className="secondary" onClick={()=>setModal(false)}>Done</button></div></div>}
 <section className="card table"><table><thead><tr><th>BOM / Rev</th><th>Item</th><th>Fabric</th><th>Colours</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r._id}><td>{r.bomNo} / R{r.revision}{r.isActive&&" • Active"}</td><td>{r.itemCode}<br/>{r.itemName}</td><td>{r.fabricGroup} / {r.fabricType}</td><td>{r.colours?.map(x=>x.name).join(", ")}</td><td>{r.status}{r.rejectionReason&&<small><br/>{r.rejectionReason}</small>}</td><td><button className="secondary" onClick={()=>edit(r)}>Edit</button>{r.status==="PENDING_APPROVAL"&&<><button onClick={()=>action(r,"approve")}>Approve</button><button className="danger" onClick={()=>action(r,"reject")}>Reject</button></>}</td></tr>)}</tbody></table><Empty loading={loading} rows={rows}/></section></>;}
