import { useEffect, useState } from "react";
import { api } from "../api/http.js";
import { Empty, Field, PageTitle } from "../components/Common.jsx";
export default function MasterPage({ mode }) {
  const isPo = mode === "po";
  const path = isPo ? "/masters/pos" : mode === "fabric" ? "/masters/fabrics" : "/masters/boms";
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true);
  const [form, setForm] = useState(isPo ? { poNo:"",poDate:"",deliveryDate:"",buyer:"",itemCode:"",itemName:"",style:"",bomNo:"",colour:"",orderPieces:"" } : mode === "fabric" ? { fabricCode:"",fabricGroup:"",fabricType:"",colour:"",dia:"",gsm:"" } : { bomNo:"",itemCode:"",itemName:"",brand:"",style:"",fabricGroup:"",fabricType:"",fabricPriority:1,colours:"",sizes:"",cuttingWeights:"",foldingWeights:"",status:"APPROVED" });
  const load = () => { setLoading(true); api(path).then(setRows).catch(() => setRows([])).finally(() => setLoading(false)); };
  useEffect(load, [path]);
  async function save(event) { event.preventDefault(); let data = form; if (!isPo && mode !== "fabric") { const sizes=form.sizes.split(",").map(x=>x.trim()); const cut=form.cuttingWeights.split(",").map(Number); const fold=form.foldingWeights.split(",").map(Number); if(sizes.length!==cut.length||sizes.length!==fold.length) throw new Error("Size and measurement counts must match"); data={...form,colours:form.colours.split(",").map((name,index)=>({name,priority:index+1})),sizeMeasurements:sizes.map((size,index)=>({size,cuttingWeightPerPieceKg:cut[index],foldingWeightPerPieceKg:fold[index]}))}; } if(isPo) data={...form,orderPieces:Number(form.orderPieces),colourCount:1,sizes:[{size:"ALL",orderPieces:Number(form.orderPieces)}]}; await api(path,{method:"POST",body:JSON.stringify(data)}); load(); }
  const title=isPo?"BOM and Purchase Orders":mode==="fabric"?"Fabric Master":"Garment BOM";
  return <><PageTitle title={title} text={isPo?"Delivery-date PO entry and pending visibility.":mode==="fabric"?"Fabric group, type, colour, dia and GSM master.":"Item, colour and size-wise cutting/folding measurements."} rows={rows} file={`${mode}.csv`} /><form className="card form" onSubmit={save}><h3>New {title}</h3><div className="grid">{Object.entries(form).map(([key,value]) => <Field key={key} label={key.replaceAll(/([A-Z])/g," $1")}><input required={!['buyer','brand','category','dia','gsm'].includes(key)} type={key.toLowerCase().includes('date')?'date':key.toLowerCase().includes('priority')||key.toLowerCase().includes('pieces')?'number':'text'} value={value} onChange={(e)=>setForm({...form,[key]:e.target.value})} /></Field>)}</div><button type="submit">Save</button></form><section className="card table"><table><thead><tr><th>Reference</th><th>Item / Fabric</th><th>Style / Colour</th><th>Date / Dia</th><th>Status / Qty</th></tr></thead><tbody>{rows.map(row=><tr key={row._id}><td>{row.poNo||row.bomNo||row.fabricCode}</td><td>{row.itemName||row.fabricType}</td><td>{row.style||row.colour}</td><td>{String(row.deliveryDate||row.dia||"").slice(0,10)}</td><td>{row.status||row.orderPieces||row.gsm}</td></tr>)}</tbody></table><Empty loading={loading} rows={rows}/></section></>;
}
