import { useEffect,useState } from "react";import { api,downloadCsv } from "../api/http.js";import { Empty,PageTitle } from "../components/Common.jsx";
export default function PurchaseOrderPage(){const[pos,setPos]=useState([]),[batches,setBatches]=useState([]),[review,setReview]=useState([]),[batch,setBatch]=useState(null),[loading,setLoading]=useState(true),[range,setRange]=useState({from:"",to:""});
 const load=()=>{setLoading(true);Promise.all([api(`/masters/pos?${new URLSearchParams(range)}`),api("/masters/po-uploads")]).then(([p,b])=>{setPos(p);setBatches(b)}).finally(()=>setLoading(false))};useEffect(load,[]);
 const upload=async e=>{e.preventDefault();const file=e.currentTarget.file.files[0];if(!file)throw new Error("Select Excel file");const fd=new FormData();fd.append("file",file);await api("/masters/pos/upload",{method:"POST",body:fd});e.currentTarget.reset();load();};
 const open=async b=>{setBatch(b);setReview(await api(`/masters/po-uploads/${b._id}/rows`))};
 const decide=async(row,action)=>{const reason=action==="REJECT"?prompt("Rejection reason")||"Rejected":"";const x=await api(`/masters/po-uploads/${batch._id}/decision`,{method:"PATCH",body:JSON.stringify({decisions:[{rowId:row._id,action,reason}]})});setReview(x.rows);load();};
 return <><PageTitle title="Purchase Orders" text="Excel upload, delivery-month pending and controlled duplicate approval." rows={pos} file="purchase-orders.csv"/>
 <section className="card form"><h3>Delivery Month Report</h3><div className="inline"><input type="date" value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/><input type="date" value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/><button onClick={load}>Search</button><button className="secondary" onClick={()=>downloadCsv("po-pending.csv",pos)}>Excel Download</button></div></section>
 <form className="card form" onSubmit={upload}><h3>Upload PO Excel</h3><p>Reads Sheet1; Item Group is mapped from COLOUR sheet. Existing PO rows wait for Admin decision.</p><input name="file" type="file" accept=".xlsx,.xls" required/> <button>Upload & Validate</button></form>
 <section className="card table"><h3>PO Delivery Pending</h3><table><thead><tr><th>PO / SO</th><th>Item</th><th>Group</th><th>Delivery Month</th><th>Order Qty</th><th>Cut Completed</th><th>Cut Pending</th></tr></thead><tbody>{pos.map(r=><tr key={r._id}><td>{r.poNo}<br/>{r.soNo}</td><td>{r.itemCode}<br/>{r.itemName}</td><td>{r.itemGroup}</td><td>{r.deliveryMonthLabel}<br/>{r.orderType}</td><td>{r.orderPieces}</td><td>{r.cuttingCompletedPieces}</td><td>{r.cuttingPendingPieces}</td></tr>)}</tbody></table><Empty loading={loading} rows={pos}/></section>
 <section className="card table"><h3>Upload Audit & Approval</h3><table><thead><tr><th>File / Time</th><th>Rows</th><th>New</th><th>Duplicates</th><th>Status</th><th/></tr></thead><tbody>{batches.map(b=><tr key={b._id}><td>{b.fileName}<br/>{new Date(b.createdAt).toLocaleString()}</td><td>{b.totalRows}</td><td>{b.newRows}</td><td>{b.duplicateRows}</td><td>{b.status}</td><td><button onClick={()=>open(b)}>Review</button></td></tr>)}</tbody></table></section>
 {batch&&<div className="modalback"><div className="modal wide card"><h3>Review: {batch.fileName}</h3><div className="table"><table><thead><tr><th>PO Key</th><th>Item</th><th>Existing</th><th>Uploaded</th><th>Decision</th><th>Admin Action</th></tr></thead><tbody>{review.map(r=><tr key={r._id}><td>{r.poNo}/{r.soNo}<br/>{r.deliveryMonthLabel} • {r.orderType}</td><td>{r.itemCode}<br/>{r.itemName}</td><td>{r.existingQty}</td><td>{r.uploadedQty}</td><td>{r.decision}{r.finalQty>0&&` → ${r.finalQty}`}</td><td>{r.decision==="PENDING"&&<><button onClick={()=>decide(r,"REPLACE")}>Replace</button><button onClick={()=>decide(r,"ADD")}>Add</button><button className="danger" onClick={()=>decide(r,"REJECT")}>Reject</button></>}</td></tr>)}</tbody></table></div><button className="secondary" onClick={()=>setBatch(null)}>Close</button></div></div>}</>;}
