import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {api} from '../../api.js';
import {companyKeyFromLocation} from '../../utils/tenantClient.js';
const base='/erp/departments',labels={STITCHING:'Stitching',INWARD:'Stitched inward',CHECKING:'Checking / oil / waste',IRONING:'Ironing',PACKING:'Packing',DISPATCH:'Dispatch',WAREHOUSE:'Warehouse',SHOP:'Shop sales',MARKETING:'Marketing analysis'};
function Table({head,rows}){return <div className="erp-table"><table><thead><tr>{head.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>;}
function Field({name,type='text',required=true,label,...rest}){return <label className="erp-field"><span>{label||name}</span><input name={name} type={type} required={required} {...rest}/></label>;}
function Select({name,values,label}){return <label className="erp-field"><span>{label||name}</span><select name={name} required><option value="">Select</option>{values.map(v=><option key={v.value||v} value={v.value||v}>{v.label||v}</option>)}</select></label>;}
export function BundleTrace({bundleId,onClose}){const [data,setData]=useState(null),[qr,setQr]=useState(''),[error,setError]=useState('');const url=`${window.location.origin}/c/${companyKeyFromLocation()}/erp-bundle/${bundleId}`;useEffect(()=>{api(`${base}/trace/${bundleId}`).then(setData).catch(e=>setError(e.message));QRCode.toDataURL(url,{width:240}).then(setQr).catch(e=>setError(e.message));},[bundleId]);return <div className="erp-dialog"><div className="erp-document"><div className="erp-noprint">{onClose&&<button onClick={onClose}>Close</button>}<button onClick={()=>window.print()}>Print bundle tag / trace</button></div>{error&&<p>{error}</p>}{data&&<><h2>{data.bundle.code}</h2><p>SKU: {data.lot.sku} · Order: {data.lot.orderNo}<br/>DC: {data.lot.dcNo} · Section: {data.lot.section}<br/>Pieces: {data.bundle.qty} · Stage: {data.bundle.stage}<br/>Checking cycle: {data.bundle.cycle}</p><a href={url}><img src={qr} width="180" alt="Authenticated bundle QR"/></a><Table head={['Date','Action','Qty','User']} rows={data.events.map(e=>[new Date(e.createdAt).toLocaleString('en-IN'),e.kind,e.quantity,e.actor])}/></>}</div></div>;}
function Invoice({sale,onClose}){const amt=v=>'₹'+(Number(v||0)/100).toFixed(2);return <div className="erp-dialog"><div className="erp-document"><div className="erp-noprint"><button onClick={onClose}>Close</button><button onClick={()=>window.print()}>Print invoice / PDF</button></div><h2>{sale.totals.tax?'Tax invoice':'Sales invoice — no GST charged'}</h2><h3>{sale.supplier?.name}</h3><p>{sale.supplier?.address}<br/>{sale.supplier?.gstin&&`GSTIN: ${sale.supplier.gstin}`}</p><p>Invoice: {sale.number} · Shop: {sale.shop}<br/>Date: {new Date(sale.createdAt).toLocaleDateString('en-IN')}<br/>Customer: {sale.customer?.name||'Walk-in'}<br/>{sale.customer?.gstin&&`Customer GSTIN: ${sale.customer.gstin}`}</p><Table head={['SKU','Qty','Net','Tax','Total']} rows={[[sale.sku,sale.quantity,amt(sale.totals.net),amt(sale.totals.tax),amt(sale.totals.gross)]]}/>{sale.taxType==='CGST_SGST'?<p>CGST: {amt(Math.floor(sale.totals.tax/2))} · SGST: {amt(sale.totals.tax-Math.floor(sale.totals.tax/2))}</p>:sale.taxType==='IGST'?<p>IGST: {amt(sale.totals.tax)}</p>:null}<p>Paid by {sale.paymentMode}. Returns: {sale.returned} pieces.</p></div></div>;}
export default function Departments({notify}){
 const [catalog,setCatalog]=useState(null),[department,setDepartment]=useState(''),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[trace,setTrace]=useState(null),[invoice,setInvoice]=useState(null),[analysis,setAnalysis]=useState(null),[demands,setDemands]=useState([]),[corrections,setCorrections]=useState([]),[materialRows,setMaterialRows]=useState(Array.from({length:10},()=>({sku:'',quantity:1,perPieces:1}))),[key,setKey]=useState(crypto.randomUUID());
 const canWrite=catalog?.writeDepartments.includes(department);
 async function load(d=department){if(d)setData(await api(`${base}/${d}/dashboard`));if(d==='MARKETING')setDemands(await api(`${base}/demands`));if(d==='CHECKING')try{setCorrections(await api(`${base}/corrections`));}catch{setCorrections([]);}}
 useEffect(()=>{api(`${base}/catalog`).then(c=>{setCatalog(c);setDepartment(c.departments[0]||'');}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{setData(null);setAnalysis(null);load().catch(e=>setError(e.message));},[department]);
 async function submit(e,path,extra={}){e.preventDefault();const form=e.currentTarget,payload={...Object.fromEntries(new FormData(form)),...extra,key};setBusy(true);setError('');try{const actualPath=path==='demand-decision'?`demands/${payload.demandId}/decision`:path;const result=await api(`${base}/${actualPath}`,{method:'POST',body:JSON.stringify(payload)});setKey(crypto.randomUUID());form.reset();await load();notify?.('Saved');if(result.details?.sale)setInvoice(result.details.sale);}catch(err){setError(err.message);}finally{setBusy(false);}}
 const bundles=data?.bundles||[],bundleOptions=bundles.map(b=>({value:b._id,label:`${b.code} · ${b.stage} · ${b.qty} pcs`}));
 const form=(path,children,extra={})=><form className="erp-grid" onSubmit={e=>submit(e,path,extra)}>{children}<button disabled={busy}>Save {path}</button></form>;
 return <section className="erp-card"><h2>Production to retail departments</h2><nav className="erp-tabs">{catalog?.departments.map(d=><button key={d} onClick={()=>{setDepartment(d);setError('');setKey(crypto.randomUUID());}} className={d===department?'active':''}>{labels[d]}</button>)}</nav>{error&&<p className="erp-error">{error}</p>}{catalog&&!catalog.departments.length&&<p>No department enabled or permitted. Ask your company administrator.</p>}<h3>{labels[department]}</h3><button onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button>
 {department==='STITCHING'&&canWrite&&<><h4>Reusable operation master (one SKU represents colour + size)</h4>{form('masters',<><Field name="masterKey" label="Unique master version key"/><Field name="sku"/><Field name="name"/><Field name="operationText" label="Operations, comma-separated"/></>,{kind:'STITCHING'})}<h4>Section delivery from reviewed core stock</h4>{form('delivery',<><Field name="sku"/><Field name="orderNo"/><Field name="dcNo"/><Field name="section"/><Field name="quantity" type="number" min="1" step="1"/><Select name="sourceLocation" values={['CUTTING','FINISHED']}/><Field name="operationMaster"/><Field name="packingMaster"/></>)}</>}
 {department==='PACKING'&&canWrite&&<><h4>Size/SKU-specific packing master</h4><form onSubmit={e=>submit(e,'masters',{kind:'PACKING',materials:materialRows.filter(r=>r.sku).map(r=>({...r,sku:r.sku.toUpperCase()}))})}><div className="erp-grid"><Field name="masterKey"/><Field name="sku"/><Field name="name"/></div>{materialRows.map((r,i)=><div className="erp-grid" key={i}><label>Material SKU<input value={r.sku} onChange={e=>setMaterialRows(materialRows.map((v,j)=>i===j?{...v,sku:e.target.value}:v))}/></label><label>Material quantity<input type="number" min="0.001" step="0.001" value={r.quantity} onChange={e=>setMaterialRows(materialRows.map((v,j)=>i===j?{...v,quantity:e.target.value}:v))}/></label><label>Per pieces / carton capacity<input type="number" min="1" step="1" value={r.perPieces} onChange={e=>setMaterialRows(materialRows.map((v,j)=>i===j?{...v,perPieces:e.target.value}:v))}/></label></div>)}<button type="button" onClick={()=>setMaterialRows([...materialRows,{sku:'',quantity:1,perPieces:1}])}>Add material</button><button disabled={busy}>Save packing master version</button></form><h4>Pack ironed pieces into carton / bundle</h4>{form('pack',<><Select name="bundleId" values={bundleOptions}/><Field name="quantity" type="number" min="1"/></>)}</>}
 {['WAREHOUSE','SHOP'].includes(department)&&canWrite&&<><h4>{department} master</h4>{form('masters',<><Field name="masterKey"/><Field name="name"/></>,{kind:department})}</>}
 {['STITCHING','INWARD','CHECKING','IRONING'].includes(department)&&canWrite&&<><h4>Advance / receive / complete selected operation</h4>{form('advance',<><Select name="bundleId" values={bundleOptions}/><Field name="quantity" type="number" min="1"/><Field name="operator" required={false}/><Field name="shift" required={false}/></>)}</>}
 {department==='CHECKING'&&canWrite&&<><h4>Checking split — good / rework / oil / reject</h4>{form('check',<><Select name="bundleId" values={bundleOptions}/>{['good','rework','oil','reject'].map(k=><Field key={k} name={k} type="number" min="0" defaultValue="0"/>)}<Field name="defect"/></>)}</>}
 {['PACKING','DISPATCH','WAREHOUSE','SHOP'].includes(department)&&canWrite&&<><h4>Dispatch / receive transfer (receipt may be partial)</h4>{form('transfer',<><Select name="bundleId" values={bundleOptions}/><Field name="quantity" type="number" min="1"/><Field name="destination" label="Warehouse/shop master key; receiving keeps existing destination" required={false}/></>)}</>}
 {department==='SHOP'&&canWrite&&<><h4>Retail sale / invoice</h4>{form('sale',<><Select name="bundleId" values={bundleOptions}/><Field name="quantity" type="number" min="1"/><Field name="unitPrice" type="number" min="0" step="0.01"/><Field name="discount" type="number" min="0" step="0.01" defaultValue="0"/><Select name="taxPercent" values={['0','5','12','18','28']}/><Select name="taxType" values={['NO_TAX','CGST_SGST','IGST']}/><Select name="paymentMode" values={['CASH','BANK']}/>{['customerName','customerPhone','customerEmail','customerGstin'].map(k=><Field key={k} name={k} required={false}/>)}</>)}<h4>Return and refund — pieces go to checking</h4>{form('return',<><Select name="saleId" values={(data?.sales||[]).map(s=>({value:s._id,label:`${s.number} · ${s.quantity-s.returned} returnable`}))}/><Field name="quantity" type="number" min="1"/><Field name="reason"/></>)}</>}
 {department==='MARKETING'&&<><form className="erp-grid" onSubmit={async e=>{e.preventDefault();setError('');try{setAnalysis(await api(`${base}/marketing/analysis?${new URLSearchParams(new FormData(e.currentTarget))}`));}catch(err){setError(err.message);}}}><Field name="days" type="number" defaultValue="30" min="1" max="365"/><Field name="leadDays" type="number" defaultValue="14" min="0"/><Field name="safety" type="number" defaultValue="0" min="0"/><button>Analyze demand</button></form>{analysis&&<><p>{analysis.note}</p><Table head={['Shop','SKU','Net sold','Returns','Stock','In transit','Suggested replenishment']} rows={analysis.rows.map(r=>[r.shop,r.sku,r.sold,r.returns,r.stock,r.inTransit,r.suggested])}/></>}</>}
 {data?.lots.length>0&&<><h4>Section DC pending — original dispatch remains unchanged</h4><Table head={['Lot','DC','Section','SKU','Sent','Inward','Pending']} rows={data.lots.map(l=>[l.code,l.dcNo,l.section,l.sku,l.sent,l.received,l.sent-l.received])}/></>}
 {department==='CHECKING'&&canWrite&&<><h4>Reverse an unused movement (company administrator only)</h4>{form('undo',<><Select name="eventId" values={corrections.map(e=>({value:e._id,label:e.kind+" · "+new Date(e.createdAt).toLocaleString("en-IN")+" · "+e.quantity+" pcs"}))}/><Field name="reason"/><Field name="confirm" label="Type UNDO MOVEMENT"/></>)}<h4>Approved waste disposal (company administrator only)</h4>{form('waste-disposal',<><Select name="bundleId" values={bundleOptions.filter(o=>o.label.includes('WASTE'))}/><Field name="quantity" type="number" min="1"/><Field name="reason"/></>)}</>}
 {department==='MARKETING'&&<><h4>Reviewed replenishment requests</h4>{canWrite&&form('demands',<><Field name="sku"/><Field name="shop"/><Field name="quantity" type="number" min="1"/><Field name="reason"/></>)}<Table head={['Number / demand ID','Shop','SKU','Qty','Status','Requested by']} rows={demands.map(d=>[d.number+" / "+d._id,d.shop,d.sku,d.quantity,d.status,d.requestedBy])}/>{canWrite&&form('demand-decision',<><Select name="demandId" values={demands.filter(d=>d.status==='PENDING').map(d=>({value:d._id,label:d.number}))}/><Select name="status" values={['APPROVED','REJECTED']}/><Field name="notes" label="Decision notes (independent company admin)"/></>)}<p>Approved requests are planning inputs. Create a WORK_ORDER in Integrated ERP using the approved demand ID and reviewed BOM. Allocations cannot exceed approved pieces. Purchase orders remain reviewed procurement entries.</p></>}
 <h4>Current physical bundles / stage quantities</h4><Table head={['Bundle','Stage','Qty','Destination','Cycle','QR / history']} rows={bundles.map(b=>[b.code,b.stage.startsWith('OP:')?((data?.lots.find(l=>String(l._id)===b.lotId)?.operations[Number(b.stage.slice(3))]||b.stage)+' · operation pending'):b.stage,b.qty,b.destination||'—',b.cycle,<button onClick={()=>setTrace(b._id)}>View / QR</button>])}/>
 {canWrite&&bundles.length>0&&<><h4>Split bundle / carton</h4>{form('split',<><Select name="bundleId" values={bundleOptions}/><Field name="quantity" type="number" min="1"/></>)}</>}
 {department==='SHOP'&&<Table head={['Invoice','SKU','Qty','Returned','Print']} rows={(data?.sales||[]).map(s=>[s.number,s.sku,s.quantity,s.returned,<button onClick={()=>setInvoice(s)}>Invoice</button>])}/>}
 {trace&&<BundleTrace bundleId={trace} onClose={()=>setTrace(null)}/>} {invoice&&<Invoice sale={invoice} onClose={()=>setInvoice(null)}/>}
 </section>;
}
