import { Router } from "express";
import { asyncHandler } from "../utils/asyncHandler.js";
import { foldingIssues, machineByQr, machines, machineTimeline, queue, resumeMachine, saveCuttingActual, saveMachine, startMachine, stopMachine } from "../controllers/cuttingController.js";
const router = Router();
router.get("/queue", asyncHandler(queue));
router.get("/machines", asyncHandler(machines));
router.post("/machines", asyncHandler(saveMachine));
router.get("/machines/qr/:qrToken", asyncHandler(machineByQr));
router.post("/machines/start", asyncHandler(startMachine));
router.patch("/runs/:runNo/stop", asyncHandler(stopMachine));
router.patch("/runs/:runNo/resume", asyncHandler(resumeMachine));
router.get("/machines/:machineCode/timeline", asyncHandler(machineTimeline));
router.post("/actual", asyncHandler(saveCuttingActual));
router.get("/folding", asyncHandler(foldingIssues));
export default router;
