import { Router } from "express";
import { asyncHandler } from "../utils/asyncHandler.js";
import multer from "multer";
import { approveBom, decidePoRows, listBoms, listFabrics, listPoBatches, listPos, listPoUploadRows, rejectBom, saveBom, saveFabric, savePo, uploadPos } from "../controllers/masterController.js";
const router = Router();
const upload = multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024}});
router.get("/boms", asyncHandler(listBoms));
router.post("/boms", asyncHandler(saveBom));
router.patch("/boms/:id/approve", asyncHandler(approveBom));
router.patch("/boms/:id/reject", asyncHandler(rejectBom));
router.get("/fabrics", asyncHandler(listFabrics));
router.post("/fabrics", asyncHandler(saveFabric));
router.get("/pos", asyncHandler(listPos));
router.post("/pos", asyncHandler(savePo));
router.post("/pos/upload", upload.single("file"), asyncHandler(uploadPos));
router.get("/po-uploads", asyncHandler(listPoBatches));
router.get("/po-uploads/:batchId/rows", asyncHandler(listPoUploadRows));
router.patch("/po-uploads/:batchId/decision", asyncHandler(decidePoRows));
export default router;
