import GarmentBom from "../models/GarmentBom.js";
import FabricMaster from "../models/FabricMaster.js";
import GarmentPurchaseOrder from "../models/GarmentPurchaseOrder.js";
import PoUploadBatch from "../models/PoUploadBatch.js";
import PoUploadRow from "../models/PoUploadRow.js";
import CuttingActual from "../models/CuttingActual.js";
import FabricOutward from "../models/FabricOutward.js";
import { nextBomNo, prepareMeasurements } from "../services/bomService.js";
import { parsePoWorkbook } from "../services/poExcelService.js";

const scope=r=>({companyId:r.tenant.companyId,factoryId:r.tenant.factoryId});
const admin=r=>{if(!["admin","super_admin","saas_super_admin"].includes(r.tenant.role))throw Object.assign(new Error("Admin approval required"),{statusCode:403});};
const poKey=(r,x)=>({...scope(r),poNo:x.poNo,soNo:x.soNo||"",itemCode:x.itemCode,deliveryMonthLabel:x.deliveryMonthLabel,orderType:x.orderType||"REGULAR"});

export async function listBoms(r,s){s.json(await GarmentBom.find(scope(r)).sort({bomNo:1,revision:-1}));}
export async function saveBom(r,s){const old=r.body._id?await GarmentBom.findOne({_id:r.body._id,...scope(r)}):null,bomNo=old?.bomNo||await nextBomNo(r.tenant),revision=old?Math.max(...await GarmentBom.find({...scope(r),bomNo}).distinct("revision"),0)+1:1,data={...r.body};delete data._id;const row=await GarmentBom.create({...data,bomNo,revision,parentRevisionId:old?._id||null,isActive:false,status:"PENDING_APPROVAL",numberOfColours:Number(data.numberOfColours||data.colours?.length||1),sizeMeasurements:prepareMeasurements(data.sizeMeasurements),submittedBy:r.tenant.updatedBy,...scope(r),updatedBy:r.tenant.updatedBy});s.status(201).json(row);}
export async function approveBom(r,s){admin(r);const row=await GarmentBom.findOne({_id:r.params.id,...scope(r)});if(!row)throw Object.assign(new Error("BOM revision not found"),{statusCode:404});await GarmentBom.updateMany({...scope(r),bomNo:row.bomNo,isActive:true},{$set:{isActive:false}});Object.assign(row,{status:"APPROVED",isActive:true,approvedBy:r.tenant.updatedBy,approvedAt:new Date(),rejectionReason:""});await row.save();s.json(row);}
export async function rejectBom(r,s){admin(r);const row=await GarmentBom.findOneAndUpdate({_id:r.params.id,...scope(r)},{$set:{status:"REJECTED",isActive:false,rejectionReason:r.body.reason||"Rejected by admin",updatedBy:r.tenant.updatedBy}},{new:true});if(!row)throw Object.assign(new Error("BOM revision not found"),{statusCode:404});s.json(row);}
export async function listFabrics(r,s){s.json(await FabricMaster.find(scope(r)).sort({fabricGroup:1,fabricType:1,colour:1}));}
export async function saveFabric(r,s){s.status(201).json(await FabricMaster.findOneAndUpdate({...scope(r),fabricCode:r.body.fabricCode,colour:r.body.colour,dia:r.body.dia||"",gsm:r.body.gsm||0},{...r.body,...scope(r),updatedBy:r.tenant.updatedBy},{upsert:true,new:true,runValidators:true}));}
export async function listPos(r,s){const f=scope(r);if(r.query.from||r.query.to)f.deliveryDate={...(r.query.from&&{$gte:new Date(r.query.from)}),...(r.query.to&&{$lte:new Date(`${r.query.to}T23:59:59.999Z`)})};const pos=await GarmentPurchaseOrder.find(f).sort({deliveryDate:1}).lean(),outs=await FabricOutward.find(scope(r)).select("outwardNo poNo itemCode").lean(),map=new Map(outs.map(x=>[x.outwardNo,`${x.poNo}|${x.itemCode}`])),actual=await CuttingActual.find(scope(r)).select("outwardNo totalActualPieces").lean(),totals={};actual.forEach(x=>{const k=map.get(x.outwardNo);if(k)totals[k]=(totals[k]||0)+x.totalActualPieces;});s.json(pos.map(x=>{const done=totals[`${x.poNo}|${x.itemCode}`]||x.cuttingCompletedPieces||0;return{...x,cuttingCompletedPieces:done,cuttingPendingPieces:Math.max(0,x.orderPieces-done)}}));}
export async function savePo(r,s){const d=r.body,label=d.deliveryMonthLabel||new Date(d.deliveryDate).toLocaleString("en",{month:"short",year:"2-digit"}).toUpperCase().replace(" ","-");s.status(201).json(await GarmentPurchaseOrder.findOneAndUpdate(poKey(r,{...d,deliveryMonthLabel:label}),{...d,deliveryMonthLabel:label,...scope(r),updatedBy:r.tenant.updatedBy},{upsert:true,new:true,runValidators:true}));}
async function applyRow(r,batch,row,qty){return GarmentPurchaseOrder.findOneAndUpdate(poKey(r,row),{poNo:row.poNo,soNo:row.soNo,itemCode:row.itemCode,itemName:row.itemName,itemGroup:row.itemGroup,deliveryDate:row.deliveryDate,deliveryMonthLabel:row.deliveryMonthLabel,orderType:row.orderType,poDate:new Date(),orderPieces:qty,sourceUploadBatch:String(batch._id),...scope(r),updatedBy:r.tenant.updatedBy},{upsert:true,new:true,runValidators:true});}
export async function uploadPos(r,s){if(!r.file)throw Object.assign(new Error("Select an Excel file"),{statusCode:400});const data=parsePoWorkbook(r.file.buffer),batch=await PoUploadBatch.create({fileName:r.file.originalname,totalRows:data.length,uploadedBy:r.tenant.updatedBy,...scope(r),updatedBy:r.tenant.updatedBy});let fresh=0,dupes=0;for(const row of data){const old=await GarmentPurchaseOrder.findOne(poKey(r,row)),duplicate=Boolean(old);duplicate?dupes++:fresh++;await PoUploadRow.create({...row,batchId:batch._id,existingQty:old?.orderPieces||0,isDuplicate:duplicate,decision:duplicate?"PENDING":"CREATE",finalQty:duplicate?0:row.uploadedQty,...scope(r),updatedBy:r.tenant.updatedBy});if(!duplicate)await applyRow(r,batch,row,row.uploadedQty);}Object.assign(batch,{newRows:fresh,duplicateRows:dupes,approvedRows:fresh,status:dupes?"PENDING_APPROVAL":"COMPLETED"});await batch.save();s.status(201).json({batch,rows:await PoUploadRow.find({batchId:batch._id,...scope(r)})});}
export async function listPoBatches(r,s){s.json(await PoUploadBatch.find(scope(r)).sort({createdAt:-1}));}
export async function listPoUploadRows(r,s){s.json(await PoUploadRow.find({...scope(r),batchId:r.params.batchId}).sort({rowNo:1}));}
export async function decidePoRows(r,s){admin(r);const batch=await PoUploadBatch.findOne({_id:r.params.batchId,...scope(r)});if(!batch)throw Object.assign(new Error("Upload batch not found"),{statusCode:404});for(const d of r.body.decisions||[]){const row=await PoUploadRow.findOne({_id:d.rowId,batchId:batch._id,...scope(r)});if(!row||row.decision!=="PENDING")continue;const action=String(d.action||"").toUpperCase();if(!["REPLACE","ADD","REJECT"].includes(action))throw Object.assign(new Error("Use REPLACE, ADD or REJECT"),{statusCode:400});const qty=action==="REPLACE"?row.uploadedQty:action==="ADD"?row.existingQty+row.uploadedQty:0;if(action!=="REJECT")await applyRow(r,batch,row,qty);Object.assign(row,{decision:action,finalQty:qty,decisionReason:d.reason||"",decidedBy:r.tenant.updatedBy,decidedAt:new Date()});await row.save();}const pending=await PoUploadRow.countDocuments({...scope(r),batchId:batch._id,decision:"PENDING"});batch.approvedRows=await PoUploadRow.countDocuments({...scope(r),batchId:batch._id,decision:{$in:["CREATE","REPLACE","ADD"]}});batch.rejectedRows=await PoUploadRow.countDocuments({...scope(r),batchId:batch._id,decision:"REJECT"});batch.status=pending?"PARTIAL":"COMPLETED";batch.approvedBy=r.tenant.updatedBy;batch.approvedAt=new Date();await batch.save();s.json({batch,rows:await PoUploadRow.find({...scope(r),batchId:batch._id})});}
