import test from 'node:test';
import assert from 'node:assert/strict';
import {pieces,names,checkSplit,stageAfter,packingRequirements,saleTotals,demandSuggestion,allowedShop,allowedDepartment,enabledDepartment} from '../src/erp/departmentPolicy.js';
test('whole piece quantities reject fractional/unsafe/negative input',()=>{for(const v of [0,-1,1.2,true,'',null,1000001])assert.throws(()=>pieces(v));assert.equal(pieces('300'),300);});
test('reusable operation names reject duplicate or empty operations',()=>{assert.deepEqual(names(['Join','Hem']),['Join','Hem']);assert.throws(()=>names(['Hem','Hem']));assert.throws(()=>names(['']));});
test('checking conserves partial quantity and prevents over classification',()=>{assert.deepEqual(checkSplit({good:240,rework:30,oil:20,reject:10},300),{good:240,rework:30,oil:20,reject:10,total:300});assert.throws(()=>checkSplit({good:301},300));assert.throws(()=>checkSplit({oil:-1},300));assert.equal(checkSplit({good:20},300).total,20);});
test('operation sequence and rework/oil cycles return to checking',()=>{const ops=['Join','Hem'];assert.equal(stageAfter('STITCHING_READY',ops),'OP:0');assert.equal(stageAfter('OP:0',ops),'OP:1');assert.equal(stageAfter('OP:1',ops),'STITCHED');assert.equal(stageAfter('STITCHED',ops),'CHECKING');assert.equal(stageAfter('REWORK',ops),'REWORK_DONE');assert.equal(stageAfter('REWORK_DONE',ops),'CHECKING');assert.equal(stageAfter('OIL_DONE',ops),'CHECKING');assert.equal(stageAfter('GOOD',ops),'IRONING');assert.equal(stageAfter('IRONING',ops),'IRONED');assert.throws(()=>stageAfter('OP:9',ops));});
test('packing materials use per-piece or rounded carton capacity',()=>{assert.deepEqual(packingRequirements([{sku:'BAG',quantity:1,perPieces:1},{sku:'BOX',quantity:1,perPieces:50}],75),[{sku:'BAG',qty:75000},{sku:'BOX',qty:2000}]);assert.throws(()=>packingRequirements([{sku:'X',quantity:1e100,perPieces:1}],1));});
test('cash sale supports GST and no GST and rejects negative discounted net',()=>{assert.deepEqual(saleTotals(10,100,18,50),{net:95000,tax:17100,gross:112100});assert.deepEqual(saleTotals(1,100,0),{net:10000,tax:0,gross:10000});assert.throws(()=>saleTotals(1,100,0,101));assert.throws(()=>saleTotals(1,100,101));});
test('demand suggestion subtracts shop stock and in-transit',()=>{assert.equal(demandSuggestion(300,30,14,10,50,20),80);assert.equal(demandSuggestion(0,30,14,0,50,20),0);assert.throws(()=>demandSuggestion(3,0,14,0,0,0));});
test('department grants never give owner customer access or cross-department write',()=>{assert.equal(allowedDepartment({role:'saas_super_admin',permissions:['department.shop.write']},'SHOP',true),false);assert.equal(allowedDepartment({role:'department_entry',permissions:['department.shop.write']},'SHOP',true),true);assert.equal(allowedDepartment({role:'department_entry',permissions:['department.shop.write']},'WAREHOUSE',true),false);assert.equal(allowedDepartment({role:'department_entry',permissions:['department.shop.read']},'SHOP',true),false);});
test('company selection and explicit plan department license both apply',()=>{assert.equal(enabledDepartment({enabledDepartments:['SHOP'],entitlements:{modules:['ERP_CORE','SHOP']}},'SHOP'),true);assert.equal(enabledDepartment({enabledDepartments:['SHOP'],entitlements:{modules:['ERP_CORE','WAREHOUSE']}},'SHOP'),false);assert.equal(enabledDepartment({enabledDepartments:['SHOP']},'PACKING'),false);});

test("shop grants isolate cashier locations",()=>{assert.equal(allowedShop({role:"department_entry",permissions:["department.shop.write","shop.AA"]},"AA"),true);assert.equal(allowedShop({role:"department_entry",permissions:["department.shop.write","shop.AA"]},"BB"),false);assert.equal(allowedShop({role:"saas_super_admin",permissions:[]},"AA"),false);});
